[global]
daemonize = yes
error_log = /tmp/php-fpm-error.log
pid = /tmp/php-fpm.pid

[www]
listen = 127.0.0.1:9001
listen.allowed_clients = 127.0.0.1
user = nobody
group = nogroup
pm = ondemand
pm.max_children = 8
pm.process_idle_timeout = 10s
pm.max_requests = 500
clear_env = no
catch_workers_output = yes
php_admin_value[error_log] = /tmp/php-error.log
php_admin_flag[log_errors] = on
