[global]
error_log = /tmp/php-fpm-error.log
pid = /tmp/php-fpm.pid

[www]
listen = 127.0.0.1:9001
listen.allowed_clients = 127.0.0.1
user = nobody
group = nogroup
pm = static
pm.max_children = 5
clear_env = no
catch_workers_output = yes
php_admin_value[error_log] = /tmp/php-error.log
php_admin_flag[log_errors] = on
